---
# System Attributes
# -----------------------------

# Chose between circle and half_circle
boxes_arrangement_type : circle
boxes_arrangement_angle_offset : 0

# "Box half circle": Radius of the half circle on which the 
# boxes of the system will be positioned. 
# The Box half circle equals the box_half_circle_radius_factor 
# is the factor times the maximal dimension of the boxes 
# (max of box_rect_width and box_rect_height)

box_circle_radius : 
box_circle_radius_factor : 1.2

box_half_circle_radius : 
box_half_circle_radius_factor : 1.7

# Box Rect Attributes
# -----------------------------
box_rect_width : 300
box_rect_height : 300
box_rect_color : lightgrey
box_rect_opacity : 0.7
box_rect_stroke_color : black
box_rect_stroke_opacity : 1
box_rect_stroke_width : 5

box_title_font_size : 20
box_title_font_color : black
# Relative position of the title within the box_rect
box_title_rel_pos_horizontal : 0.5  
box_title_rel_pos_vertical : 0.1

box_subrect_width_relative : 0.9
box_subrect_top_margin_relative : 0.05
box_subrect_color : darkgrey
box_subrect_opacity : 0.5
box_subrect_stroke_color : darkgrey
box_subrect_stroke_opacity : 0.1
box_subrect_stroke_width : 1

box_info_font_size : 12
box_info_font_color : black

...
